BIN := mkr
VERSION := 0.1.1
CURRENT_REVISION := $(shell git rev-parse --short HEAD)
BUILD_LDFLAGS := "-w -s -X main.gitcommit=$(CURRENT_REVISION)"

export GO111MODULE=on

.PHONY: all
all: clean cross test rpm deb
